### PR TITLE
Rethinking labels - namespaces are disabled by default

### PR DESCRIPTION
**Pull request by catalin-ilea**

### CODE REVIEW

**Comment by rossedman** [comment]
@catalin-ilea @george-angel Sorry to post this here, but question on this:

I am running this and I can confirm a couple of things:

1. My files are pulled and placed in directory as expected
2. My files are structured in namespace format
3. `kube-applier` is running and trying to apply
4. There are no errors
5. If I exec into container I can manually apply manifests

However, nothing ever gets deployed. I thought it had something to do with this commit since it isn't documented for the most part, if I do this it still doesn't work:

```
apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
  labels:
    automaticDeployment: "On"
```

Am I missing something? Thanks

Logs:
```
2018/03/01 23:51:54 Full run interval (1m0s) reached, queueing run.
2018/03/01 23:51:54 Run queued.
2018/03/01 23:51:54 Started apply run at 2018-03-01 23:51:54.152226716 +0000 UTC m=+181.007261925
2018/03/01 23:51:54 Applying dir /k8s/resources/manifests/bootstrap/kube-system
2018/03/01 23:51:54 Applying dir /k8s/resources/manifests/bootstrap/nginx-ingress
2018/03/01 23:51:54 Finished apply run at 2018-03-01 23:51:54.497582069 +0000 UTC m=+181.352617249
```

**Comment by george-angel** [comment]
Could you show us the content of your `/k8s/resources/manifests/bootstrap/kube-system` directory? Via `find .` or `tree .`

**Comment by rossedman** [comment]
@george-angel I got this working using one of the 0.4.0 containers that exist. Seems to work well. Is there a way to turn the prune piece off? Concerned I might blow away some stuff I didn't intend. Will post tree when on desktop. Thanks so much for response. The work on this fork is great. Read all the PRs

**Comment by george-angel** [comment]
Not yet, I created an Issue for it: https://github.com/utilitywarehouse/kube-applier/issues/14

We will pick it as soon as someone has time, alternatively feel free to raise a PR.

**Comment by rossedman** [comment]
@george-angel great I will take a look at it! Thanks

**Pull request merged**
